/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as WeekRouteImport } from './routes/week'
import { Route as AlexaLinkRouteImport } from './routes/alexa/link'
import { Route as ApiAlexaRouteImport } from './routes/api/alexa'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAlexaOauthAuthorizeRouteImport } from './routes/api/alexa.oauth.authorize'
import { Route as ApiAlexaOauthTokenRouteImport } from './routes/api/alexa.oauth.token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)
const AlexaLinkRoute = AlexaLinkRouteImport.update({
  id: '/alexa/link',
  path: '/alexa/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlexaRoute = ApiAlexaRouteImport.update({
  id: '/api/alexa',
  path: '/api/alexa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlexaOauthAuthorizeRoute = ApiAlexaOauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => ApiAlexaRoute,
} as any)
const ApiAlexaOauthTokenRoute = ApiAlexaOauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => ApiAlexaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/routines': typeof RoutinesRoute
  '/week': typeof WeekRoute
  '/alexa/link': typeof AlexaLinkRoute
  '/api/alexa': typeof ApiAlexaRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/alexa/oauth/authorize': typeof ApiAlexaOauthAuthorizeRoute
  '/api/alexa/oauth/token': typeof ApiAlexaOauthTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/routines': typeof RoutinesRoute
  '/week': typeof WeekRoute
  '/alexa/link': typeof AlexaLinkRoute
  '/api/alexa': typeof ApiAlexaRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/alexa/oauth/authorize': typeof ApiAlexaOauthAuthorizeRoute
  '/api/alexa/oauth/token': typeof ApiAlexaOauthTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/login': typeof LoginRoute
  '/routines': typeof RoutinesRoute
  '/week': typeof WeekRoute
  '/alexa/link': typeof AlexaLinkRoute
  '/api/alexa': typeof ApiAlexaRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/alexa/oauth/authorize': typeof ApiAlexaOauthAuthorizeRoute
  '/api/alexa/oauth/token': typeof ApiAlexaOauthTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/login'
    | '/routines'
    | '/week'
    | '/alexa/link'
    | '/api/alexa'
    | '/api/auth/$'
    | '/api/alexa/oauth/authorize'
    | '/api/alexa/oauth/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/login'
    | '/routines'
    | '/week'
    | '/alexa/link'
    | '/api/alexa'
    | '/api/auth/$'
    | '/api/alexa/oauth/authorize'
    | '/api/alexa/oauth/token'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/login'
    | '/routines'
    | '/week'
    | '/alexa/link'
    | '/api/alexa'
    | '/api/auth/$'
    | '/api/alexa/oauth/authorize'
    | '/api/alexa/oauth/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  LoginRoute: typeof LoginRoute
  RoutinesRoute: typeof RoutinesRoute
  WeekRoute: typeof WeekRoute
  AlexaLinkRoute: typeof AlexaLinkRoute
  ApiAlexaRoute: typeof ApiAlexaRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alexa/link': {
      id: '/alexa/link'
      path: '/alexa/link'
      fullPath: '/alexa/link'
      preLoaderRoute: typeof AlexaLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alexa': {
      id: '/api/alexa'
      path: '/api/alexa'
      fullPath: '/api/alexa'
      preLoaderRoute: typeof ApiAlexaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alexa/oauth/authorize': {
      id: '/api/alexa/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/api/alexa/oauth/authorize'
      preLoaderRoute: typeof ApiAlexaOauthAuthorizeRouteImport
      parentRoute: typeof ApiAlexaRoute
    }
    '/api/alexa/oauth/token': {
      id: '/api/alexa/oauth/token'
      path: '/oauth/token'
      fullPath: '/api/alexa/oauth/token'
      preLoaderRoute: typeof ApiAlexaOauthTokenRouteImport
      parentRoute: typeof ApiAlexaRoute
    }
  }
}

interface ApiAlexaRouteChildren {
  ApiAlexaOauthAuthorizeRoute: typeof ApiAlexaOauthAuthorizeRoute
  ApiAlexaOauthTokenRoute: typeof ApiAlexaOauthTokenRoute
}

const ApiAlexaRouteChildren: ApiAlexaRouteChildren = {
  ApiAlexaOauthAuthorizeRoute: ApiAlexaOauthAuthorizeRoute,
  ApiAlexaOauthTokenRoute: ApiAlexaOauthTokenRoute,
}

const ApiAlexaRouteWithChildren = ApiAlexaRoute._addFileChildren(
  ApiAlexaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  LoginRoute: LoginRoute,
  RoutinesRoute: RoutinesRoute,
  WeekRoute: WeekRoute,
  AlexaLinkRoute: AlexaLinkRoute,
  ApiAlexaRoute: ApiAlexaRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
